---
- name: Installing and Launch packetbeat in linux
  hosts: usrNodes
  become: yes
  vars:
    local_user: 
    curr_version: 7.13.2
    # input the user where config files will be
    # TDOD: Make it so that the packetbeat.yml can be editied per interface currently set to 'any'
  tasks:

    # Use command module
  - name: Download packetbeat 
    unarchive: 
      src: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-{{ curr_version }}-linux-x86_64.tar.gz
      dest: /usr/local/bin/
      remote_src: True
      validate_certs: True
      #mode: 0775

    # Use copy module
  - name: Drop in packetbeat.yml
    copy: 
      src: "/users/{{ local_user }}/packetbeat.yml"
      dest: /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/
      mode: '0644'


  # use the file module
     
  - name: Setting proper permissions on packetbeat
    become_method: sudo
    become_user: root
    file:
      path: /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/packetbeat.yml
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"
      mode: '0644'

  - name: Running Setup
    become_method: sudo
    become_user: root
    shell: /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/packetbeat setup -e -c /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/packetbeat.yml

  - name: Drop in packetbeat.service unit file
    become_method: sudo
    become_user: root
    copy: 
      src: "/users/{{ local_user }}/packetbeat.service"
      dest: /etc/systemd/system/packetbeat.service
      mode: '0644'

  - name: Setup unit file Working Directory
    replace:
      path: /etc/systemd/system/packetbeat.service
      after: 'WorkingDirectory='
      regexp: '\b(WorkingDirectory=)'
      replace: /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/

  - name: Setup unit file ExecStart
    replace:
      path: /etc/systemd/system/packetbeat.service
      after: 'ExecStart='
      regexp: '\b(ExecStart=)'
      replace: /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/packetbeat -e -c /usr/local/bin/packetbeat-{{ curr_version }}-linux-x86_64/packetbeat.yml

  - name: Rebooting systemd daemon('s)
    become_method: sudo
    become_user: root
    systemd:
      daemon_reload: yes
  
  - name: Starting packetbeat Service
    become_method: sudo
    become_user: root
    service:
      name: packetbeat
      state: restarted
      enabled: yes

