---
# sample playbook for filebeats
- name: Testing setup of filebeat
  gatherfacts: true
  hosts: usrNodes #This is what I think it should be 
  # infers that ssh is already avaible to the elk node
  become: yes
  tasks: # found on https://uci.bootcampcontent.com/EmperorForgotten/elk-stack-project/blob/master/Ansible-Playbooks/filebeat-playbook.yml
  
  - name: Install and setup filebeat
    roles:
      - role: elastic.beats
    vars:
      beats_version: 7.13.2
      beat: filebeat
      beat_conf:
        filebeat:
          inputs:
            - type: log
              enabled: true
              paths:
                - /var/log/*.log

  - name: Install and setup packetbeat # https://github.com/elastic/ansible-beats
    roles:
      - { role: beats, beat: "packetbeat",
        beat_conf: {
          "interfaces": {"device":"any"},
          "protocols": {
            "dns": {
              "ports": [53],
              "include_authorities":true
            },
            "http": {
              "ports": [80, 8080, 8000, 5000, 8002]
            },
            "memcache": {
              "ports": [11211]
            },
            "mysql": {
              "ports": [3306]
            },
            "pgsql": {
              "ports": [5432]
            },
            "redis": {
              "ports": [6379]
            },
            "thrift": {
              "ports": [9090]
            },
            "mongodb": {
              "ports": [27017]
            }
          }
        },
        output_conf : {
          "elasticsearch": {
            "hosts": ["localhost:9200"]
          }
        }
    }
  vars:
    use_repository: "true"