---
#https://github.com/elastic/ansible-beats 
# this is trying to use the roles funcitionality 
- name: Installing and Launch Filebeat
  hosts: usrNodes
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.13.2
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log