---
- name: Installing and Launching ELK Stack
  # infers CentOs machine with yum package manager 
  hosts: meas_node
  become: yes
  vars:
    local_user: 
    #curr_version: 
    docker_compose_ver: 1.25.5
    usr_name_elk: 
    passwd_elk: 
    # input the user where config files will be
  tasks:

  - name: Remove docker if installed from CentOS repo
    yum:
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      state: removed

  - name: yum-clean-metadata # clean meta data for setup
    command: yum clean metadata
    args:
      warn: no

  - name: Installing Tooling for Stack via Yum
    yum:
      name: 
        - epel-release 
        - gcc 
        - openssl-devel 
        - bzip2-devel
        - libffi-devel
        - centos-release-scl
        - yum-utils
        - ansible
        - git
        - httpd-tools
        - lvm2
        - device-mapper-persistent-data
      state: latest
      update_cache: true
      

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
  
  - name: Install Docker
    yum:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

- name: Rebooting systemd daemon('s) # to make sure everything is nice and clean
  systemd:
    daemon_reload: yes

 - name: Starting Docker Daemon
   service:
     name: docker
     state: restarted
     enabled: yes
      

  # https://lastviking.eu/install_docker_on_centos_with_ansible.html

  # this seciton is for base install of docker / docker-compose

  

  #- name: Add user {{ local_user}} to docker group
  #  user:
  #    name: ' {{ local_user }} '
  #    groups: docker
  #    append: yes
  # ^ casused ansible to break and print out'y' on repeat in the issuing terminal

  - name: Check if Docker Compose is installed
    command: docker-compose --version
    register: docker_compose_check
    ignore_errors: yes

  - name: Check Docker install
    shell: docker run hello-world

  - name: Setting vm.max_map_count
    shell: sysctl -w vm.max_map_count=262144 

  - name: Remove standard hosts file
    file:
      path: /etc/ansible/hosts
      state: absent

  - name: Move hosts file into meas_node
    copy: 
      src: "/users/{{ local_user }}/hosts"
      dest: /etc/ansible/hosts
      mode: '0644'

  #- name: Adding local user to docker-compose
   # shell: usermod -aG docker {{ local_user }}

  - name: Download and install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755
    when:
      - docker_compose_check.msg is defined
      - docker_compose_check.msg.find('No such file or directory') != -1

  - name: Install ELK stack via Git
    git:
      repo: https://github.com/fabric-testbed/fabric-docker-images.git
      dest: /usr/bin/fabric_base

  - name: Setting Folders for ELK Stack
    shell: /usr/bin/fabric_base/elk/setfolders.sh

  - name: Setting login info for nginx
    shell: htpasswd -b -c  /usr/bin/fabric_base/elk/nginx/etc/.htpasswd.user {{ usr_name_elk }} {{ passwd_elk }}

  - name: Drop in ELK_Stack.service unit file
    copy: 
      src: "/users/{{ local_user }}/ELK_Stack.service"
      dest: /etc/systemd/system/ELK_Stack.service
      mode: '0644'

  - name: Rebooting systemd daemon('s)
    systemd:
      daemon_reload: yes
  
  - name: Starting ELK Service
    service:
      name: ELK_Stack
      state: restarted
      enabled: yes

    # dirty way for the system to start detached and then come back up after intsall
    # this is so the script does not hang

